export const weatherMap = {
  0: { desc: "Clear Sky", icon: "☀️" },
  1: { desc: "Mainly Clear", icon: "🌤️" },
  2: { desc: "Partly Cloudy", icon: "⛅" },
  3: { desc: "Overcast", icon: "☁️" },
  45: { desc: "Misty", icon: "🌫️" },
  48: { desc: "Foggy", icon: "🌫️" },
  51: { desc: "Light Drizzle", icon: "🌧️" },
  53: { desc: "Moderate Drizzle", icon: "🌧️" },
  55: { desc: "Heavy Drizzle", icon: "🌧️" },
  61: { desc: "Slight Rain", icon: "🌧️" },
  63: { desc: "Moderate Rain", icon: "🌧️" },
  65: { desc: "Heavy Rain", icon: "⛈️" },
  71: { desc: "Slight Snow", icon: "❄️" },
  73: { desc: "Moderate Snow", icon: "❄️" },
  75: { desc: "Heavy Snow", icon: "❄️" },
  77: { desc: "Snow Grains", icon: "❄️" },
  80: { desc: "Slight Showers", icon: "🌧️" },
  81: { desc: "Moderate Showers", icon: "🌧️" },
  82: { desc: "Violent Showers", icon: "⛈️" },
  85: { desc: "Slight Snow Showers", icon: "❄️" },
  86: { desc: "Heavy Snow Showers", icon: "❄️" },
  95: { desc: "Thunderstorm", icon: "⛈️" },
  96: { desc: "Thunderstorm with Hail", icon: "⛈️" },
  99: { desc: "Thunderstorm with Heavy Hail", icon: "⛈️" },
};
